hostname: "localhost"
port: 5432
username: "postgres"
password: "password"
db_name: "yooo"
data_dir: "/home/tanveer/Desktop/marksheets/marksheets/"
processed_dir: "/home/tanveer/Desktop/marksheets/processed/"
